import { SnapletClient } from '@snaplet/seed';
import { faker } from '@faker-js/faker/locale/es_MX'

// This is a basic example generated by Snaplet to start you off, check out the docs for where to go from here
// * For more on getting started with @snaplet/seed: https://docs.snaplet.dev/getting-started/quick-start/seed
// * For a more detailed reference: https://docs.snaplet.dev/core-concepts/seed

const snaplet = new SnapletClient({
  dryRun: process.env.DRY !== '0',
});

// Clears all existing data in the database, but keep the structure
await snaplet.$resetDatabase()

// auth users
await snaplet.users([{
  instance_id: "00000000-0000-0000-0000-000000000000",
  id: "0a830161-2854-4b36-84a3-94ccf9184257",
  aud: "authenticated",
  role: "authenticated",
  email: "yosept.flores@gmail.com",
  encrypted_password: "$2a$10$NnBBS1xoBsI20zhGSZdhYuJuq4jSp1It7E7KdVrnlG2C.85ZLxYy6",
  email_confirmed_at: "2023-12-31 00:42:35.097475+00",
  invited_at: null,
  confirmation_token: "",
  confirmation_sent_at: null,
  recovery_token: "",
  recovery_sent_at: null,
  email_change: "",
  email_change_token_new: "",
  email_change_sent_at: null,
  last_sign_in_at: null,
  raw_app_meta_data: { "provider": "email", "providers": ["email"] },
  raw_user_meta_data: {},
  is_super_admin: null,
  created_at: "2023-12-31 00:42:35.093882+00",
  updated_at: "2023-12-31 00:42:35.097616+00",
  phone: null,
  phone_confirmed_at: null,
  phone_change: "",
  phone_change_token: "",
  email_change_token_current: "",
  email_change_confirm_status: 0,
  banned_until: null,
  reauthentication_token: "",
  reauthentication_sent_at: null,
  is_sso_user: false,
  deleted_at: null,
  phone_change_sent_at: null,
}])

const emptyNode = {
  deletedAt: null,
  updatedAt: null,
}

const emptyState = {
  east: null,
  north: null,
  south: null,
  west: null,
  ...emptyNode,
}

const statesAndIds = [
  {
    name: "BAJA_CALIFORNIA_NORTE",
    id: "ChIJ0913qAxw14ARjt4YA5_9pPw",
  },
  {
    name: "BAJA_CALIFORNIA_SUR",
    id: "ChIJyR6itTnTr4YRGFmnqTqz33E",
  },
  {
    name: "CAMPECHE",
    id: "ChIJFeLHS0LD6IURw_yqe4z3i-Y",
  },
  {
    name: "CHIAPAS",
    id: "ChIJZ85Xl7REjYURFdYZRoIzAM8",
  },
  {
    name: "CHIHUAHUA",
    id: "ChIJCaSRhS91loYRB36nQFPig5s",
  },
  {
    name: "COAHUILA",
    id: "ChIJKR6Opr1yiIYROXrNFNeaAGQ",
  },
  {
    name: "COLIMA",
    id: "ChIJ6yVw_g0yJYQRCmlXH5dAHiw",
  },
  {
    name: "DURANGO",
    id: "ChIJSUVzr8GpkIYRsgjjq0HifSk",
  },
  {
    name: "CUERNAVACA",
    id: "ChIJR_72Ja7fzYURD91poSWCX5cs",
  },
  {
    name: "GUANAJUATO",
    id: "ChIJf3-bUI9bK4QRoEO-gRmmjuc",
  },
  {
    name: "GUERRERO",
    id: "ChIJPyAn81hly4UROst3QpsiNzE",
  },
  {
    name: "HIDALGO",
    id: "ChIJ5y_OIgQK0YURG3hAeb_FUoE",
  },
  {
    name: "JALISCO",
    id: "ChIJb05i1OtAH4QRU0obWqOw_qA",
  },
  {
    name: "MEXICO_CITY",
    id: "ChIJJyk1sTYAzoURW4rR6E6e_d4",
  },
  {
    name: "MICHOACAN",
    id: "ChIJt1yzHj5fKoQR1OBL8wxlxzs",
  },
  {
    name: "MORELOS",
    id: "ChIJR_72Ja7fzYURD91poSWCX5c",
  },
  {
    name: "NAYARIT",
    id: "ChIJR9s-5pyoIIQROdKUhqL1yMI",
  },
  {
    name: "NUEVO_LEON",
    id: "ChIJXbClooSVYoYRxrtsw0L0HXA",
  },
  {
    name: "OAXACA",
    id: "ChIJUVwOOk_YwIURyQvZPUMMxkQ",
  },
  {
    name: "PUEBLA",
    id: "ChIJZafA3bCMz4URrSAC1luuXOI",
  },
  {
    name: "QUERETARO",
    id: "ChIJX3BEYdFE04URu2lIpMSxRpE",
  },
  {
    name: "QUINTANA_ROO",
    id: "ChIJlSbD6vD8T48RnI1MSCrF8MQ",
  },
  {
    name: "SAN_LUIS_POTOSI",
    id: "ChIJefusBQCiKoQRXkEExEGyIOY",
  },
  {
    name: "SINALOA",
    id: "ChIJWUmnKJRTn4YR71--DXbfe5w",
  },
  {
    name: "SONORA",
    id: "ChIJD9JN52kpmIYRdOO7_Br_Vs0",
  },
  {
    name: "STATE_OF_MEXICO",
    id: "ChIJOwrrwJKJzYURV6jFn775_sI",
  },
  {
    name: "TABASCO",
    id: "ChIJT8t4j1_77YURRGuG2RHLJtQ",
  },
  {
    name: "TAMAULIPAS",
    id: "ChIJWSQe265TeYYRJRnoNVqfhTM",
  },
  {
    name: "TLAXCALA",
    id: "ChIJE2EAHD_Zz4UR4L181Friujg",
  },
  {
    name: "VERACRUZ",
    id: "ChIJbVJUr9BVw4URs7kQZwp_dy0",
  },
  {
    name: "YUCATAN",
    id: "ChIJ7QTWqvgPVI8RCj0IMXUhzMw",
  },
  {
    name: "ZACATECAS",
    id: "ChIJb_7JfqDRgYYRmG0lXv0tHxw",
  }
].map(x => ({ ...x, ...emptyState }))

await snaplet.$pipe([
  snaplet.$merge([
    snaplet.Customer([{
      email: "yosept.flores@mail.com",
      name: "Joseph Flores",
      ...emptyNode,
    }]),
    snaplet.Customer(x => x(3, () => {
      const name = faker.person.fullName()
      return {
        email: faker.internet.email({ firstName: name.split(' ')[0], lastName: name.split(' ')[1] }),
        name,
        ...emptyNode,
      }
    }
    )),
  ]),
  snaplet.Billboard(x => x(15, () => ({
    address: faker.location.streetAddress(),
    postCode: faker.location.zipCode(),
    ...emptyNode, 
  })), { autoConnect: true }),
  snaplet.Place(statesAndIds),
  snaplet.BillboardInPlace(x => x(15, () => emptyNode), { autoConnect: true }),
]);